### ISSUE TITLE
Seems like visitFile() aplies only to regular files, so you don't need to check it

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW01#1]
https://github.com/Garuda-1/JA-HW01/blob/533f9771128920f143d744a1ed6fdee5d7ebf878/src/ru/ifmo/rain/dolzhanskii/walk/RecursiveWalk.java#L21

**Comment by Garuda-1** [comment]
I had the same thought. Did you manage to find a documentation reference confirming this?

**Comment by Garuda-1** [comment]
Anyway, fixed.

**Comment by Deletrius366** [comment]
https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileVisitor.html#visitFile(T,%20java.nio.file.attribute.BasicFileAttributes)
Since it is written "Invoked for a file in a directory.", we can presume it.
