### ISSUE TITLE
Are you sure, new File() works fine if file doesn't exist?

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW01#3]
https://github.com/Garuda-1/JA-HW01/blob/57edfe4203b6c3dd8544fd6e0ba158d492c715be/src/ru/ifmo/rain/dolzhanskii/walk/RecursiveWalk.java#L70

**Comment by Garuda-1** [comment]
Yes, according to the documentation:
https://docs.oracle.com/javase/8/docs/api/java/io/PrintWriter.html#PrintWriter-java.lang.String-

**Comment by Deletrius366** [comment]
Why you show me PrintWriter docs? I meant File class
